/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

export = {
  configs: {
    recommended: import("./configs/recommended"),
  },
  rules: {
    "must-use-result": import("./rules/must-use-result")
  },
};
